title: Contribute
content: |
    <div class="jumbotron">
      <H1>Contribute . . </h1>
      <p class="lead"><b>We need you!</b></p>
      <p>Help us make Teacher Virus the best source of free education on the planet that's developed in a sustainable way.<p>
      <p> Whatever your path - take the first step in participation by registering for the Alpha:</p>
      <a class="btn btn-success" href="http://www.teachervirus.org/register" role="button">Register! »</a>
    </div>
    
    #Once Registered . .
    
    
    ##Get Infected!

    Install Teacher Virus on the device of your choice (mainly Android at this point) and give it a go.  

    <a class="btn btn-success" href="?/get-infected/" role="button">Get Infected »</a>
    
    Once infected, join the conversation in the Teacher Virus forum and tell us what you want from the platform and provide feedback to the various payload developers so that we can quickly iterate our work.
    
      <p> <a class="btn btn-primary" href="https://groups.google.com/forum/#!forum/teacher-virus" role="button">Forum for Teacher Virus Infected »</a></p>
      
    ##Mutate Payloads
    
    Anyone with enough determination can create a Payload for Teacher Virus!
    
    For example - if you don't yet have the ability to write code then we suggest you have a look at something like Twine to get you started.
    
    <a class="btn btn-success" href="http://www.twinery.org" role="button">Twine »</a>
    
    If you do have the ability to write HTML and Javascript (and maybe even PHP) then you can consider taking on building more challenging Payloads.
    
    Either way have a look at the OATSEA GitHub account to get you started:
    
    <a class="btn btn-success" href="https://github.com/OATSEA" role="button">OATSEA GitHub »</a>
    
    Once you have something you'd like to share with the community - upload your code to a public github repository in the same way as the payloads currently available under the OATSEA Account and let us know your GitHub details and we will share your work with the rest of the community.
    
    If you need help or suggestions come talk to the rest of the Mutator community in the dedicated Mutator forum!
    
    <p> <a class="btn btn-primary" href="https://groups.google.com/d/forum/teacher-virus-mutators" role="button">Forum for Teacher Virus Mutators »</a></p>
    
    For further information on how to Mutate Teacher Virus have a look here:
    
    <p> <a class="btn btn-success" href="?/contribute/mutate/" role="button">Mutating Teacher Virus »</a></p>  
    
    ##Breed It!
    
    If you are a developer we'd love your help in developing the underlying Teacher Virus platform - Help us breed the virus that provides the best free education on the planet!
    
    <a class="btn btn-success" href="http://www.teachervirus.org/contact" role="button">Contact Us »</a>
  
