title: Get Infected!
content: |
  <div class="well">
    <h1>Join the Alpha</h1>
    <p>We're looking for people to play with us who are passionate about the power of education to change the world and want to get involved in solving some of humanities' greatest challenges through (self) education.</p>
    <p>If you'd like to <b>participate in the Alpha</b> as either a student, tester, developer or teacher (or something else) please contact us and register at OATSEA:</p>
    <p><a class="btn lrg btn-default" href="http://teachervirus.org/register">Register! </a></p>
    <h3>... Or you can just get infected by following the instructions below </h3>
  </div>
  
    <div class="jumbotron"><h1>For Android . . </h1>
  <p><b>Step 1:</b> Download, Install and Start a Web server on your Android device - For example <a href="/infect/DroidPHP.apk" >DroidPHP</a></p>
  <p><a class="btn lrg btn-success" href="/infect/DroidPHP.apk" >Get DropidPHP</a></p>
  <p><b>Step 2:</b> Download, Install and Start the <a href="/infect/teachervirus.apk">Teacher Virus App (APK file)</a></p>
  <p><a class="btn lrg btn-success" href="/infect/teachervirus.apk">Get Teacher Virus for Android</a></p>
  
  <p><b>Note:</b> You will need to authorise installation of non marketplace apps in your Android Settings</p>
  <p>If you have any problems - talk to us by registering officially for the Alpha.
  </div>
  
  
  
  ##Other Devices?
  
  **Step 1:** Download & Install a Web server of your choice (e.g. Apache or Lighttpd and PHP) on the device of your choice (e.g. Raspberry Pi, laptop/desktop). 
  
  **Step 2:** Download and unzip <a href="/infect/getinfected.php.zip">getinfected.php</a> to the "root" of your web server's public folder (e.g. htdocs, public_html or /var/www on raspberry Pi)
  
  **Step 3:** Open a web browser and access that file on your webserver (http://localhost/getinfected.php) and it will install Teacher Virus from GitHub. 
  
  **Note:** If you encounter an error you may need to set file & folder permissions on various files to 755 depending on the configuration of your server .
  
  ##Having Trouble?
  
  If you have problems getting infected (installing) please register for the Alpha and join the community to get assistance!
  
  ##Warning!
  
  We don't recommend installing Teacher Virus on a live / public website at this point (It's an Alpha!).
  
  We recommend for security reasons that you turn off the web server when you put your device on a public/untrusted network due to the alpha nature of Teacher Virus. 
  
  In short; as Teacher Virus is currently only at alpha it's not yet ready for production use and **its use is at your own risk.**
