bypass_cache: true
title: Contact
content: |
  Contact the creators of Teacher Virus online:
  
  <p> <a class="btn btn-primary" href="http://www.teachervirus.org/contact" role="button" target="_blank">Contact Us Online »</a></p>
  
