title: Payloads
content: |
    <div class="jumbotron">
      <H1>Payloads</h1>
        <p>Payloads are the point of Teacher Virus.</p>
        <p>You can get an idea how they work from the online Teacher Virus demo:</p>
         <p><a class="btn lrg btn-success" href="/play" role="button"><b class="glyphicon glyphicon-play-circle"></b> Play Teacher Virus Payloads »</a></p>
        <p>We refer to the educational apps, games and content that are available on Teacher Virus as <b>"Payloads"</b>.  Other systems call this stuff apps, components, modules, blocks, pages etc.</p>
        <p>Any "thing" written in HTML 5 (Javascript) / PHP and shared on Github can be provided as a Teacher Virus payload.  If you'd like your contribution included for others to play with then contact us and join the Alpha.</p>
        <p>We don't have all the answers on how to create the <b>best free education on the planet</b>.  That's why we're instead focusing on ways to enable you to do it and have it easily distributed and curated!<p>
        <p>As things progress we will provide the ability for the Teacher Virus community to easily contribute, curate and rate payloads. </p> 
        <p>We're also working on a way to allow the wider community to patronise these contributions in order to make building free / open source education sustainable (more on that soon!).</p>
        <p>In the event we make it to the finals of the XPRIZE we will then put the winnings back into the community by co-funding the patronisation of the community as a way of fairly identifying who should be rewarded for their involvement in the development of <b>free education</b> that enables kids (and adults) in need, to learn how to read, write and do math.</p>
        <p>But even if we don't make it to the XPRIZE finals we are committed to building a sustainable way of providing quality free education through the power of community and technology!<p>
        <p>Have a look at how you can contribute to Teacher Virus for more details!</p>
         <p><a class="btn lrg btn-primary" href="?/contribute/" role="button"></b> Contribute »</a></p>
    </div>
